/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapChainRouteImport } from './routes/map-chain'
import { Route as IndexRouteImport } from './routes/index'

const MapChainRoute = MapChainRouteImport.update({
  id: '/map-chain',
  path: '/map-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map-chain': typeof MapChainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map-chain': typeof MapChainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map-chain': typeof MapChainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/map-chain'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/map-chain'
  id: '__root__' | '/' | '/map-chain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapChainRoute: typeof MapChainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map-chain': {
      id: '/map-chain'
      path: '/map-chain'
      fullPath: '/map-chain'
      preLoaderRoute: typeof MapChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapChainRoute: MapChainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
